/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.Sample;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.records.SampleUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleUser extends TableImpl<SampleUserRecord> {

    private static final long serialVersionUID = 161875531;

    /**
     * The reference instance of <code>SAMPLE.SAMPLE_USER</code>
     */
    public static final SampleUser SAMPLE_USER = new SampleUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SampleUserRecord> getRecordType() {
        return SampleUserRecord.class;
    }

    /**
     * The column <code>SAMPLE.SAMPLE_USER.ID_USER</code>.
     */
    public final TableField<SampleUserRecord, Long> ID_USER = createField("ID_USER", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SAMPLE.SAMPLE_USER.NM_USER</code>.
     */
    public final TableField<SampleUserRecord, String> NM_USER = createField("NM_USER", org.jooq.impl.SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>SAMPLE.SAMPLE_USER.LOGIN_USER</code>.
     */
    public final TableField<SampleUserRecord, String> LOGIN_USER = createField("LOGIN_USER", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>SAMPLE.SAMPLE_USER.PWD_USER</code>.
     */
    public final TableField<SampleUserRecord, String> PWD_USER = createField("PWD_USER", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>SAMPLE.SAMPLE_USER</code> table reference
     */
    public SampleUser() {
        this(DSL.name("SAMPLE_USER"), null);
    }

    /**
     * Create an aliased <code>SAMPLE.SAMPLE_USER</code> table reference
     */
    public SampleUser(String alias) {
        this(DSL.name(alias), SAMPLE_USER);
    }

    /**
     * Create an aliased <code>SAMPLE.SAMPLE_USER</code> table reference
     */
    public SampleUser(Name alias) {
        this(alias, SAMPLE_USER);
    }

    private SampleUser(Name alias, Table<SampleUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private SampleUser(Name alias, Table<SampleUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SampleUser(Table<O> child, ForeignKey<O, SampleUserRecord> key) {
        super(child, key, SAMPLE_USER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sample.SAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ID_USER_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SampleUserRecord> getPrimaryKey() {
        return Keys.ID_USER_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SampleUserRecord>> getKeys() {
        return Arrays.<UniqueKey<SampleUserRecord>>asList(Keys.ID_USER_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleUser as(String alias) {
        return new SampleUser(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleUser as(Name alias) {
        return new SampleUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SampleUser rename(String name) {
        return new SampleUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SampleUser rename(Name name) {
        return new SampleUser(name, null);
    }
}
