/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables;


import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.Indexes;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.Keys;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.Sample;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.records.SampleOrderProductRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleOrderProduct extends TableImpl<SampleOrderProductRecord> {

    private static final long serialVersionUID = -820169306;

    /**
     * The reference instance of <code>SAMPLE.SAMPLE_ORDER_PRODUCT</code>
     */
    public static final SampleOrderProduct SAMPLE_ORDER_PRODUCT = new SampleOrderProduct();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SampleOrderProductRecord> getRecordType() {
        return SampleOrderProductRecord.class;
    }

    /**
     * The column <code>SAMPLE.SAMPLE_ORDER_PRODUCT.ID_ORDER_PRODUCT</code>.
     */
    public final TableField<SampleOrderProductRecord, Long> ID_ORDER_PRODUCT = createField("ID_ORDER_PRODUCT", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SAMPLE.SAMPLE_ORDER_PRODUCT.ID_ORDER</code>.
     */
    public final TableField<SampleOrderProductRecord, Long> ID_ORDER = createField("ID_ORDER", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>SAMPLE.SAMPLE_ORDER_PRODUCT.ID_PRODUCT</code>.
     */
    public final TableField<SampleOrderProductRecord, Long> ID_PRODUCT = createField("ID_PRODUCT", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>SAMPLE.SAMPLE_ORDER_PRODUCT</code> table reference
     */
    public SampleOrderProduct() {
        this(DSL.name("SAMPLE_ORDER_PRODUCT"), null);
    }

    /**
     * Create an aliased <code>SAMPLE.SAMPLE_ORDER_PRODUCT</code> table reference
     */
    public SampleOrderProduct(String alias) {
        this(DSL.name(alias), SAMPLE_ORDER_PRODUCT);
    }

    /**
     * Create an aliased <code>SAMPLE.SAMPLE_ORDER_PRODUCT</code> table reference
     */
    public SampleOrderProduct(Name alias) {
        this(alias, SAMPLE_ORDER_PRODUCT);
    }

    private SampleOrderProduct(Name alias, Table<SampleOrderProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private SampleOrderProduct(Name alias, Table<SampleOrderProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SampleOrderProduct(Table<O> child, ForeignKey<O, SampleOrderProductRecord> key) {
        super(child, key, SAMPLE_ORDER_PRODUCT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sample.SAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ID_ORDER_PRODUCT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SampleOrderProductRecord> getPrimaryKey() {
        return Keys.ID_ORDER_PRODUCT_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SampleOrderProductRecord>> getKeys() {
        return Arrays.<UniqueKey<SampleOrderProductRecord>>asList(Keys.ID_ORDER_PRODUCT_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SampleOrderProductRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SampleOrderProductRecord, ?>>asList(Keys.ID_ORDER_FK, Keys.ID_PRODUCT_FK);
    }

    public SampleOrder sampleOrder() {
        return new SampleOrder(this, Keys.ID_ORDER_FK);
    }

    public SampleProduct sampleProduct() {
        return new SampleProduct(this, Keys.ID_PRODUCT_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderProduct as(String alias) {
        return new SampleOrderProduct(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderProduct as(Name alias) {
        return new SampleOrderProduct(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SampleOrderProduct rename(String name) {
        return new SampleOrderProduct(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SampleOrderProduct rename(Name name) {
        return new SampleOrderProduct(name, null);
    }
}
