/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.oracle.model.jooq;


import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleDishe;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrder;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrderProduct;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleProduct;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleRestaurant;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sample extends SchemaImpl {

    private static final long serialVersionUID = -984841696;

    /**
     * The reference instance of <code>SAMPLE</code>
     */
    public static final Sample SAMPLE = new Sample();

    /**
     * The table <code>SAMPLE.SAMPLE_DISHE</code>.
     */
    public final SampleDishe SAMPLE_DISHE = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleDishe.SAMPLE_DISHE;

    /**
     * The table <code>SAMPLE.SAMPLE_ORDER</code>.
     */
    public final SampleOrder SAMPLE_ORDER = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrder.SAMPLE_ORDER;

    /**
     * The table <code>SAMPLE.SAMPLE_ORDER_PRODUCT</code>.
     */
    public final SampleOrderProduct SAMPLE_ORDER_PRODUCT = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrderProduct.SAMPLE_ORDER_PRODUCT;

    /**
     * The table <code>SAMPLE.SAMPLE_PRODUCT</code>.
     */
    public final SampleProduct SAMPLE_PRODUCT = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleProduct.SAMPLE_PRODUCT;

    /**
     * The table <code>SAMPLE.SAMPLE_RESTAURANT</code>.
     */
    public final SampleRestaurant SAMPLE_RESTAURANT = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleRestaurant.SAMPLE_RESTAURANT;

    /**
     * The table <code>SAMPLE.SAMPLE_USER</code>.
     */
    public final SampleUser SAMPLE_USER = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleUser.SAMPLE_USER;

    /**
     * No further instances allowed
     */
    private Sample() {
        super("SAMPLE", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SAMPLE_DISHE_SEQ,
            Sequences.SAMPLE_ORDER_PRODUCT_SEQ,
            Sequences.SAMPLE_ORDER_SEQ,
            Sequences.SAMPLE_PRODUCT_SEQ,
            Sequences.SAMPLE_RESTAURANT_SEQ,
            Sequences.SAMPLE_USER_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SampleDishe.SAMPLE_DISHE,
            SampleOrder.SAMPLE_ORDER,
            SampleOrderProduct.SAMPLE_ORDER_PRODUCT,
            SampleProduct.SAMPLE_PRODUCT,
            SampleRestaurant.SAMPLE_RESTAURANT,
            SampleUser.SAMPLE_USER);
    }
}
