/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.oracle.model.jooq;


import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in SAMPLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>SAMPLE.SAMPLE_DISHE_SEQ</code>
     */
    public static final Sequence<BigInteger> SAMPLE_DISHE_SEQ = new SequenceImpl<BigInteger>("SAMPLE_DISHE_SEQ", Sample.SAMPLE, org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false));

    /**
     * The sequence <code>SAMPLE.SAMPLE_ORDER_PRODUCT_SEQ</code>
     */
    public static final Sequence<BigInteger> SAMPLE_ORDER_PRODUCT_SEQ = new SequenceImpl<BigInteger>("SAMPLE_ORDER_PRODUCT_SEQ", Sample.SAMPLE, org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false));

    /**
     * The sequence <code>SAMPLE.SAMPLE_ORDER_SEQ</code>
     */
    public static final Sequence<BigInteger> SAMPLE_ORDER_SEQ = new SequenceImpl<BigInteger>("SAMPLE_ORDER_SEQ", Sample.SAMPLE, org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false));

    /**
     * The sequence <code>SAMPLE.SAMPLE_PRODUCT_SEQ</code>
     */
    public static final Sequence<BigInteger> SAMPLE_PRODUCT_SEQ = new SequenceImpl<BigInteger>("SAMPLE_PRODUCT_SEQ", Sample.SAMPLE, org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false));

    /**
     * The sequence <code>SAMPLE.SAMPLE_RESTAURANT_SEQ</code>
     */
    public static final Sequence<BigInteger> SAMPLE_RESTAURANT_SEQ = new SequenceImpl<BigInteger>("SAMPLE_RESTAURANT_SEQ", Sample.SAMPLE, org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false));

    /**
     * The sequence <code>SAMPLE.SAMPLE_USER_SEQ</code>
     */
    public static final Sequence<BigInteger> SAMPLE_USER_SEQ = new SequenceImpl<BigInteger>("SAMPLE_USER_SEQ", Sample.SAMPLE, org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(38).nullable(false));
}
