/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.oracle.model.jooq;


import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleDishe;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrder;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrderProduct;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleProduct;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleRestaurant;
import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in SAMPLE
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>SAMPLE.SAMPLE_DISHE</code>.
     */
    public static final SampleDishe SAMPLE_DISHE = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleDishe.SAMPLE_DISHE;

    /**
     * The table <code>SAMPLE.SAMPLE_ORDER</code>.
     */
    public static final SampleOrder SAMPLE_ORDER = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrder.SAMPLE_ORDER;

    /**
     * The table <code>SAMPLE.SAMPLE_ORDER_PRODUCT</code>.
     */
    public static final SampleOrderProduct SAMPLE_ORDER_PRODUCT = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrderProduct.SAMPLE_ORDER_PRODUCT;

    /**
     * The table <code>SAMPLE.SAMPLE_PRODUCT</code>.
     */
    public static final SampleProduct SAMPLE_PRODUCT = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleProduct.SAMPLE_PRODUCT;

    /**
     * The table <code>SAMPLE.SAMPLE_RESTAURANT</code>.
     */
    public static final SampleRestaurant SAMPLE_RESTAURANT = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleRestaurant.SAMPLE_RESTAURANT;

    /**
     * The table <code>SAMPLE.SAMPLE_USER</code>.
     */
    public static final SampleUser SAMPLE_USER = br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleUser.SAMPLE_USER;
}
