/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleRestaurant;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleRestaurantRecord extends UpdatableRecordImpl<SampleRestaurantRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = -839980962;

    /**
     * Setter for <code>SAMPLE.SAMPLE_RESTAURANT.ID_RESTAURANT</code>.
     */
    public void setIdRestaurant(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_RESTAURANT.ID_RESTAURANT</code>.
     */
    public Long getIdRestaurant() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_RESTAURANT.NM_RESTAURANT</code>.
     */
    public void setNmRestaurant(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_RESTAURANT.NM_RESTAURANT</code>.
     */
    public String getNmRestaurant() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_RESTAURANT.ID_DISHE</code>.
     */
    public void setIdDishe(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_RESTAURANT.ID_DISHE</code>.
     */
    public Long getIdDishe() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SampleRestaurant.SAMPLE_RESTAURANT.ID_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SampleRestaurant.SAMPLE_RESTAURANT.NM_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return SampleRestaurant.SAMPLE_RESTAURANT.ID_DISHE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNmRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getIdDishe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNmRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getIdDishe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleRestaurantRecord value1(Long value) {
        setIdRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleRestaurantRecord value2(String value) {
        setNmRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleRestaurantRecord value3(Long value) {
        setIdDishe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleRestaurantRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SampleRestaurantRecord
     */
    public SampleRestaurantRecord() {
        super(SampleRestaurant.SAMPLE_RESTAURANT);
    }

    /**
     * Create a detached, initialised SampleRestaurantRecord
     */
    public SampleRestaurantRecord(Long idRestaurant, String nmRestaurant, Long idDishe) {
        super(SampleRestaurant.SAMPLE_RESTAURANT);

        set(0, idRestaurant);
        set(1, nmRestaurant);
        set(2, idDishe);
    }
}
