/*
 * This file is generated by jOOQ.
 */
package br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.records;


import br.com.mathidios.springboot.jooq.docker.oracle.model.jooq.tables.SampleOrder;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SampleOrderRecord extends UpdatableRecordImpl<SampleOrderRecord> implements Record7<Long, Long, Long, String, LocalDate, String, Byte> {

    private static final long serialVersionUID = 1645464939;

    /**
     * Setter for <code>SAMPLE.SAMPLE_ORDER.ID_ORDER</code>.
     */
    public void setIdOrder(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_ORDER.ID_ORDER</code>.
     */
    public Long getIdOrder() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_ORDER.ID_USER</code>.
     */
    public void setIdUser(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_ORDER.ID_USER</code>.
     */
    public Long getIdUser() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_ORDER.ID_RESTAURANT</code>.
     */
    public void setIdRestaurant(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_ORDER.ID_RESTAURANT</code>.
     */
    public Long getIdRestaurant() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_ORDER.IN_STATUS_ORDER</code>.
     */
    public void setInStatusOrder(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_ORDER.IN_STATUS_ORDER</code>.
     */
    public String getInStatusOrder() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_ORDER.DT_ORDER</code>.
     */
    public void setDtOrder(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_ORDER.DT_ORDER</code>.
     */
    public LocalDate getDtOrder() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_ORDER.FL_AVAL</code>.
     */
    public void setFlAval(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_ORDER.FL_AVAL</code>.
     */
    public String getFlAval() {
        return (String) get(5);
    }

    /**
     * Setter for <code>SAMPLE.SAMPLE_ORDER.RATING</code>.
     */
    public void setRating(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>SAMPLE.SAMPLE_ORDER.RATING</code>.
     */
    public Byte getRating() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Long, String, LocalDate, String, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, Long, String, LocalDate, String, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SampleOrder.SAMPLE_ORDER.ID_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SampleOrder.SAMPLE_ORDER.ID_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return SampleOrder.SAMPLE_ORDER.ID_RESTAURANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SampleOrder.SAMPLE_ORDER.IN_STATUS_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field5() {
        return SampleOrder.SAMPLE_ORDER.DT_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SampleOrder.SAMPLE_ORDER.FL_AVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return SampleOrder.SAMPLE_ORDER.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getInStatusOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component5() {
        return getDtOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFlAval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getIdRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getInStatusOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value5() {
        return getDtOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFlAval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord value1(Long value) {
        setIdOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord value2(Long value) {
        setIdUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord value3(Long value) {
        setIdRestaurant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord value4(String value) {
        setInStatusOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord value5(LocalDate value) {
        setDtOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord value6(String value) {
        setFlAval(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord value7(Byte value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SampleOrderRecord values(Long value1, Long value2, Long value3, String value4, LocalDate value5, String value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SampleOrderRecord
     */
    public SampleOrderRecord() {
        super(SampleOrder.SAMPLE_ORDER);
    }

    /**
     * Create a detached, initialised SampleOrderRecord
     */
    public SampleOrderRecord(Long idOrder, Long idUser, Long idRestaurant, String inStatusOrder, LocalDate dtOrder, String flAval, Byte rating) {
        super(SampleOrder.SAMPLE_ORDER);

        set(0, idOrder);
        set(1, idUser);
        set(2, idRestaurant);
        set(3, inStatusOrder);
        set(4, dtOrder);
        set(5, flAval);
        set(6, rating);
    }
}
